variables:
- name: BuildParameters.workingDirectory
  value: Detox
- name: BuildParameters.searchFolder
  value: $(System.DefaultWorkingDirectory)
trigger:
  branches:
    include:
      - refs/heads/detox
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/detox
jobs:
- job: Detox_iOS_Test
  displayName: Detox iOS Test
  pool:
    vmImage: macos-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: INSTALL_NODE
    inputs:
      versionSpec: 16.x
  - task: YarnInstaller@3
    displayName: INSTALL_YARN
  - task: CmdLine@2
    displayName: INSTALL_brew_And_applesimutils
    inputs:
      script: >
        brew tap wix/brew

        brew install applesimutils
  - task: Npm@1
    displayName: INSTALL_DEPENDENCIES
    inputs:
      workingDir: $(BuildParameters.workingDirectory)
      verbose: false
  - task: CmdLine@2
    displayName: DETOX_BUILD
    inputs:
      script: >
        yarn detox:build:demo
      workingDirectory: $(BuildParameters.workingDirectory)
  - task: CmdLine@2
    displayName: DETOX_TEST
    inputs:
      script: >
        yarn detox:test:demo
      workingDirectory: $(BuildParameters.workingDirectory)
    condition: succeededOrFailed()
  - task: PublishTestResults@2
    displayName: PUBLISH_XML_TEST_RESULT
    inputs:
      testResultsFiles: '**/junit.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
...
