trigger:
  - none

pool:
  vmImage: 'macos-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.17.0'
    displayName: 'Install Node'
  
  - task: CmdLine@2
    displayName: Install Dependencies
    inputs:
      script: >
        cd Detox
        yarn install

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: 'Cache Yarn packages'

  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies'

  - script: |
      yarn codegen
      yarn type-check
    displayName: 'Codegen and type-check'

  - task: CocoaPods@0
    inputs:
      workingDirectory: 'ios'
      forceRepoUpdate: false

  - script: |
      brew tap wix/brew
      brew install applesimutils
    displayName: 'Install Detox Tools'

  - script: |
      yarn detox:build:demo
    displayName: 'Build detox project'

  - script: |
      yarn detox:test
    displayName: 'run Detox test'
